services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: panenku-backend
    env_file: ../.env.distributed
    ports: ["0.0.0.0:${BACKEND_PORT}:3000"]
    dns:
      - 100.100.100.100
    restart: unless-stopped
