services:
  postgres:
    image: postgres:16
    container_name: panenku-db
    env_file: ../.env.distributed
    ports: ["0.0.0.0:${DB_PORT}:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s

volumes:
  postgres_data:
