services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: panenku-frontend
    env_file: ../.env.distributed
    ports: ["0.0.0.0:${FRONTEND_PORT}:5173"]
    dns:
      - 100.100.100.100
    develop:
      watch:
        - action: sync
          path: ../frontend/src
          target: /app/src
        - action: rebuild
          path: ../frontend/package.json
